/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sentiment_analysis;

import AppPackage.AnimationClass;
import java.awt.Color;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import paneles.CambiaPanel;


/**
 *
 * @author bouafia
 */
public class home_pgs extends javax.swing.JFrame {

    /**
     * Creates n home_pgs
     */
    public home_pgs() {
        initComponents();
        //new CambiaPanel(panelderoite,new paneles.pnlhome());
        if(panelderoite.isVisible()){panelderoite.setVisible(false);}
        panelhome.setVisible(true);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lmodels = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        sidepane = new javax.swing.JPanel();
        btn_home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_group = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_Preparation = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_Sentiment = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btn_Component = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btn_Analysis = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        panelderoite = new javax.swing.JPanel();
        framedrag = new javax.swing.JLabel();
        panelhome = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setAlignmentX(0.0F);
        bg.setAlignmentY(0.0F);
        bg.setMinimumSize(new java.awt.Dimension(1024, 700));
        bg.setName(""); // NOI18N
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(64, 43, 100));
        jPanel4.setToolTipText("");
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lmodels.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lmodels.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/5298718-48.png"))); // NOI18N
        lmodels.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lmodelsMouseMoved(evt);
            }
        });
        lmodels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lmodelsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lmodelsMouseExited(evt);
            }
        });
        jPanel4.add(lmodels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/969265-48.png"))); // NOI18N
        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel7MouseMoved(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 60, 60));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/2890564-48.png"))); // NOI18N
        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel11MouseMoved(evt);
            }
        });
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 60, 60));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/4230300-48.png"))); // NOI18N
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel9MouseMoved(evt);
            }
        });
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 60, 60));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/2175872-48.png"))); // NOI18N
        jLabel13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel13MouseMoved(evt);
            }
        });
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 60, 60));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/3209291-48.png"))); // NOI18N
        jLabel31.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel31MouseMoved(evt);
            }
        });
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel31MouseExited(evt);
            }
        });
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 60, 60));

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/1743800-48.png"))); // NOI18N
        jLabel32.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel32MouseMoved(evt);
            }
        });
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel32MouseExited(evt);
            }
        });
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 60, 60));

        bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 60, 540));

        sidepane.setBackground(new java.awt.Color(54, 33, 89));
        sidepane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sidepane.setAlignmentX(0.0F);
        sidepane.setAlignmentY(0.0F);
        sidepane.setPreferredSize(new java.awt.Dimension(300, 400));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setBackground(new java.awt.Color(85, 65, 113));
        btn_home.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_home.setToolTipText("");
        btn_home.setName("Home"); // NOI18N
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_homeMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
        });
        btn_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Home");
        btn_home.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 13, 200, 34));
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        sidepane.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 60));

        btn_group.setBackground(new java.awt.Color(64, 43, 100));
        btn_group.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_groupMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_groupMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_groupMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_groupMouseEntered(evt);
            }
        });
        btn_group.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Working group");
        btn_group.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, -1, 20));

        sidepane.add(btn_group, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 240, 60));

        btn_Preparation.setBackground(new java.awt.Color(64, 43, 100));
        btn_Preparation.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_Preparation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_PreparationMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PreparationMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_PreparationMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_PreparationMouseEntered(evt);
            }
        });
        btn_Preparation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Prepare the environment");
        btn_Preparation.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        sidepane.add(btn_Preparation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 240, 60));

        btn_Sentiment.setBackground(new java.awt.Color(64, 43, 100));
        btn_Sentiment.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_Sentiment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_SentimentMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SentimentMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SentimentMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SentimentMouseEntered(evt);
            }
        });
        btn_Sentiment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Sentiment analysis Tweet ");
        btn_Sentiment.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 34));

        sidepane.add(btn_Sentiment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 240, 60));

        btn_dashboard.setBackground(new java.awt.Color(64, 43, 100));
        btn_dashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_dashboardMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseEntered(evt);
            }
        });
        btn_dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 18)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Dashboard");
        btn_dashboard.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 34));

        sidepane.add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 60));

        btn_Component.setBackground(new java.awt.Color(64, 43, 100));
        btn_Component.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ComponentMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ComponentMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ComponentMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ComponentMouseEntered(evt);
            }
        });
        btn_Component.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 18)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("Component programs");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        btn_Component.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        sidepane.add(btn_Component, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 240, 60));

        btn_Analysis.setBackground(new java.awt.Color(64, 43, 100));
        btn_Analysis.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_Analysis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_AnalysisMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AnalysisMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_AnalysisMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_AnalysisMouseEntered(evt);
            }
        });
        btn_Analysis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 18)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("ML model creation");
        btn_Analysis.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 34));

        sidepane.add(btn_Analysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 240, 60));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 240, 540));

        jLabel16.setBackground(java.awt.Color.white);
        jLabel16.setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 24)); // NOI18N
        jLabel16.setForeground(java.awt.Color.black);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/icons8_Multiply_32px.png"))); // NOI18N
        jLabel16.setText("-----------------------------------------------------------------------------------------------------------");
        jLabel16.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel16MouseMoved(evt);
            }
        });
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        bg.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/cerist.png"))); // NOI18N
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jPanel3.setBackground(new java.awt.Color(64, 43, 100));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 30)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("Sentiment Analysis ");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 29));

        jLabel4.setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText(" Machine Learning");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 30));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 190, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/4473024-48.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 60, 50));

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, 130));

        panelderoite.setBackground(new java.awt.Color(255, 255, 255));
        panelderoite.setMinimumSize(new java.awt.Dimension(800, 100));
        panelderoite.setName(""); // NOI18N
        panelderoite.setLayout(new javax.swing.BoxLayout(panelderoite, javax.swing.BoxLayout.LINE_AXIS));
        bg.add(panelderoite, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 1140, 670));

        framedrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                framedragMouseDragged(evt);
            }
        });
        framedrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                framedragMousePressed(evt);
            }
        });
        bg.add(framedrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 40));

        panelhome.setBackground(new java.awt.Color(255, 255, 255));
        panelhome.setMinimumSize(new java.awt.Dimension(800, 100));
        panelhome.setName(""); // NOI18N
        panelhome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/209.png"))); // NOI18N
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel21.setPreferredSize(new java.awt.Dimension(100, 100));
        jLabel21.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel21MouseMoved(evt);
            }
        });
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
        });
        panelhome.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 230, 220));

        jPanel1.setBackground(new java.awt.Color(110, 89, 222));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 18)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/5298718-128.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, 110));

        jLabel19.setFont(new java.awt.Font("Nimbus Roman No9 L", 2, 48)); // NOI18N
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setText("Home________________________");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 70));

        panelhome.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 900, 130));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/210.png"))); // NOI18N
        jLabel22.setPreferredSize(new java.awt.Dimension(100, 100));
        jLabel22.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel22MouseMoved(evt);
            }
        });
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel22MouseExited(evt);
            }
        });
        panelhome.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 230, 220));

        jLabel27.setBackground(new java.awt.Color(54, 33, 89));
        jLabel27.setFont(new java.awt.Font("Ubuntu Condensed", 1, 22)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(54, 33, 89));
        jLabel27.setText("Prepare the environment");
        panelhome.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        jLabel26.setBackground(new java.awt.Color(54, 33, 89));
        jLabel26.setFont(new java.awt.Font("Ubuntu Condensed", 1, 22)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(54, 33, 89));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("ML model creation");
        panelhome.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 200, -1));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/212.png"))); // NOI18N
        jLabel20.setPreferredSize(new java.awt.Dimension(100, 100));
        jLabel20.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel20MouseMoved(evt);
            }
        });
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel20MouseExited(evt);
            }
        });
        panelhome.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 230, 220));

        jLabel30.setBackground(new java.awt.Color(54, 33, 89));
        jLabel30.setFont(new java.awt.Font("Ubuntu Condensed", 1, 22)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(54, 33, 89));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Dashboard");
        panelhome.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 600, 220, -1));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/205.png"))); // NOI18N
        jLabel24.setPreferredSize(new java.awt.Dimension(100, 100));
        jLabel24.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel24MouseMoved(evt);
            }
        });
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel24MouseExited(evt);
            }
        });
        panelhome.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 230, 220));

        jLabel29.setBackground(new java.awt.Color(54, 33, 89));
        jLabel29.setFont(new java.awt.Font("Ubuntu Condensed", 1, 22)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(54, 33, 89));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Component Programs");
        panelhome.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 600, 220, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/206.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        panelhome.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 230, 220));

        jLabel28.setBackground(new java.awt.Color(54, 33, 89));
        jLabel28.setFont(new java.awt.Font("Ubuntu Condensed", 1, 22)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(54, 33, 89));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Work group");
        panelhome.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 600, 230, -1));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/211.png"))); // NOI18N
        jLabel23.setPreferredSize(new java.awt.Dimension(100, 100));
        jLabel23.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel23MouseMoved(evt);
            }
        });
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel23MouseExited(evt);
            }
        });
        panelhome.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, 230, 220));

        jLabel25.setFont(new java.awt.Font("Ubuntu Condensed", 1, 22)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(54, 33, 89));
        jLabel25.setText("Sentiment analysis Tweet");
        panelhome.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 320, -1, -1));
        panelhome.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 400, 270, 10));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelhome.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, 10, 240));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelhome.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 10, 250));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelhome.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 10, 250));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelhome.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 10, 240));
        panelhome.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 270, 10));
        panelhome.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 270, 10));

        bg.add(panelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 1140, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int a1=0,a2=0,a3=0,a4=0,a5=0,a6=0,a7=0;
    int b1=0,b2=0,b3=0,b4=0,b5=0,b6=0,b7=0;
    int c1=0;
    int xMouse;
    int yMouse;
    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MousePressed
        try{    
            Process proc1 = Runtime.getRuntime().exec("sh /home/bouafia/script_project/ML/Removeproc.sh");
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
        System.exit(0);
    }//GEN-LAST:event_jLabel16MousePressed

    private void btn_PreparationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PreparationMousePressed
        // TODO add your handling code here:
        setColor(btn_Preparation);
        resetColor(btn_Analysis);
        resetColor(btn_Sentiment);
        resetColor(btn_home);
        resetColor(btn_dashboard);
        resetColor(btn_group);
        resetColor(btn_Component);
        a1=0; a2=1;  a3=0;  a4=0;  a5=0;  a6=0;  a7=0;  b2=0;
    }//GEN-LAST:event_btn_PreparationMousePressed

    private void btn_AnalysisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AnalysisMousePressed
        // TODO add your handling code here:
        resetColor(btn_Preparation);
        setColor(btn_Analysis);
        resetColor(btn_Sentiment);
        resetColor(btn_home);
        resetColor(btn_dashboard);
        resetColor(btn_group);
        resetColor(btn_Component);
        a1=0; a2=0;  a3=1;  a4=0;  a5=0;  a6=0;  a7=0;  b3=0;
    }//GEN-LAST:event_btn_AnalysisMousePressed

    private void btn_SentimentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SentimentMousePressed
        // TODO add your handling code here:
        resetColor(btn_Preparation);
        resetColor(btn_Analysis);
        setColor(btn_Sentiment);
        resetColor(btn_home);
        resetColor(btn_dashboard);
        resetColor(btn_group);
        resetColor(btn_Component);
        a1=0; a2=0;  a3=0;  a4=1;  a5=0;  a6=0;  a7=0;  b4=0;
    }//GEN-LAST:event_btn_SentimentMousePressed

    private void btn_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMousePressed
        // TODO add your handling code here:
        resetColor(btn_Preparation);
        resetColor(btn_Analysis);
        resetColor(btn_Sentiment);
        setColor(btn_home);
        resetColor(btn_dashboard);
        resetColor(btn_group);
        resetColor(btn_Component);
        a1=1; a2=0;  a3=0;  a4=0;  a5=0;  a6=0;  a7=0; b1=0;
    }//GEN-LAST:event_btn_homeMousePressed

    private void btn_dashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMousePressed
        // TODO add your handling code here:
        resetColor(btn_Preparation);
        resetColor(btn_Analysis);
        resetColor(btn_Sentiment);
        resetColor(btn_home);
        setColor(btn_dashboard);
        resetColor(btn_group);
        resetColor(btn_Component);
        a1=0; a2=0;  a3=0;  a4=0;  a5=1;  a6=0;  a7=0; b5=0;
    }//GEN-LAST:event_btn_dashboardMousePressed

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        // TODO add your handling code here:
        if (a1==0){
            setColor(btn_home);
            b1=1;
        }
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        // TODO add your handling code here:
        if(b1==1){
            resetColor(btn_home);
            b1=0;
        }
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_PreparationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PreparationMouseEntered
        // TODO add your handling code here:
        if (a2==0){
            setColor(btn_Preparation);
            b2=1;
        }
    }//GEN-LAST:event_btn_PreparationMouseEntered

    private void btn_PreparationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PreparationMouseExited
        // TODO add your handling code here:
        if(b2==1){
            resetColor(btn_Preparation);
            b2=0;
        }
    }//GEN-LAST:event_btn_PreparationMouseExited

    private void btn_AnalysisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AnalysisMouseEntered
        // TODO add your handling code here:
        if (a3==0){
            setColor(btn_Analysis);
            b3=1;
        }
    }//GEN-LAST:event_btn_AnalysisMouseEntered

    private void btn_AnalysisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AnalysisMouseExited
        // TODO add your handling code here:
        if(b3==1){
            resetColor(btn_Analysis);
            b3=0;
        }
    }//GEN-LAST:event_btn_AnalysisMouseExited

    private void btn_SentimentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SentimentMouseEntered
        // TODO add your handling code here:
        if (a4==0){
            setColor(btn_Sentiment);
            b4=1;
        }
    }//GEN-LAST:event_btn_SentimentMouseEntered

    private void btn_SentimentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SentimentMouseExited
        // TODO add your handling code here:
        if(b4==1){
            resetColor(btn_Sentiment);
            b4=0;
        }
    }//GEN-LAST:event_btn_SentimentMouseExited

    private void btn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseExited
        // TODO add your handling code here:
        if(b5==1){
            resetColor(btn_dashboard);
            b5=0;
        }
    }//GEN-LAST:event_btn_dashboardMouseExited

    private void btn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseEntered
        // TODO add your handling code here:
        if (a5==0){
            setColor(btn_dashboard);
            b5=1;
        }
    }//GEN-LAST:event_btn_dashboardMouseEntered

    private void framedragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedragMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_framedragMouseDragged

    private void framedragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedragMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_framedragMousePressed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void btn_ComponentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ComponentMouseEntered
        // TODO add your handling code here:
        if (a6==0){
            setColor(btn_Component);
            b6=1;
        }
    }//GEN-LAST:event_btn_ComponentMouseEntered

    private void btn_ComponentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ComponentMouseExited
        // TODO add your handling code here:
        if(b6==1){
            resetColor(btn_Component);
            b6=0;
        }
    }//GEN-LAST:event_btn_ComponentMouseExited

    private void btn_ComponentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ComponentMousePressed
        // TODO add your handling code here:
        resetColor(btn_Preparation);
        resetColor(btn_Analysis);
        resetColor(btn_Sentiment);
        resetColor(btn_home);
        resetColor(btn_dashboard);
        resetColor(btn_group);
        setColor(btn_Component);
        a1=0; a2=0;  a3=0;  a4=0;  a5=0;  a6=1;  a7=0; b6=0;
    }//GEN-LAST:event_btn_ComponentMousePressed

    private void btn_groupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_groupMouseEntered
        // TODO add your handling code here:
         if (a7==0){
            setColor(btn_group);
            b7=1;
        }
    }//GEN-LAST:event_btn_groupMouseEntered

    private void btn_groupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_groupMouseExited
        // TODO add your handling code here:
        if(b7==1){
            resetColor(btn_group);
            b7=0;
        }
    }//GEN-LAST:event_btn_groupMouseExited

    private void btn_groupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_groupMousePressed
        // TODO add your handling code here:
        resetColor(btn_Preparation);
        resetColor(btn_Analysis);
        resetColor(btn_Sentiment);
        resetColor(btn_home);
        resetColor(btn_dashboard);
        setColor(btn_group);
        resetColor(btn_Component);
        a1=0; a2=0;  a3=0;  a4=0;  a5=0;  a6=0;  a7=1; b7=0;
    }//GEN-LAST:event_btn_groupMousePressed

    private void lmodelsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lmodelsMouseMoved
        // TODO add your handling code here:
        lmodels.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_lmodelsMouseMoved

    private void lmodelsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lmodelsMouseExited
        // TODO add your handling code here:
        lmodels.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64,43,100)));
    }//GEN-LAST:event_lmodelsMouseExited

    private void jLabel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseMoved
        // TODO add your handling code here:
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jLabel7MouseMoved

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64,43,100)));
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel11MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseMoved
        // TODO add your handling code here:
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jLabel11MouseMoved

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // TODO add your handling code here:
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64,43,100)));
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseMoved
        // TODO add your handling code here:
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jLabel9MouseMoved

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64,43,100)));
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel13MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseMoved
        // TODO add your handling code here:
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jLabel13MouseMoved

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64,43,100)));
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel32MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseMoved
        // TODO add your handling code here:
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jLabel32MouseMoved

    private void jLabel32MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseExited
        // TODO add your handling code here:
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64,43,100)));
    }//GEN-LAST:event_jLabel32MouseExited

    private void jLabel31MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseMoved
        // TODO add your handling code here:
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jLabel31MouseMoved

    private void jLabel31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseExited
        // TODO add your handling code here:
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64,43,100)));
    }//GEN-LAST:event_jLabel31MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int position = this.sidepane.getX();
        if (position > 59){
            Animacion.Animacion.mover_izquierda(60, -300, 2, 2, sidepane);
        }else{
            Animacion.Animacion.mover_derecha(-300, 60, 2, 2, sidepane);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        // TODO add your handling code here:
        panelhome.setVisible(true);
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        int position = this.panelderoite.getX();
        if (position > 1199){
            Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
        }else{
            Animacion.Animacion.mover_derecha(60, 1200, 2, 2, panelderoite);
        }
        
    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_PreparationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PreparationMouseClicked
        // TODO add your handling code here:
        panelhome.setVisible(false);
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        
        new CambiaPanel(panelderoite,new paneles.pnlpreparation());
        Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
    }//GEN-LAST:event_btn_PreparationMouseClicked

    private void btn_AnalysisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AnalysisMouseClicked
        // TODO add your handling code here:
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        panelhome.setVisible(false);
        new CambiaPanel(panelderoite,new paneles.pnlAnalysis());
        Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
    }//GEN-LAST:event_btn_AnalysisMouseClicked

    private void btn_SentimentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SentimentMouseClicked
        // TODO add your handling code here:
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        panelhome.setVisible(false);
        new CambiaPanel(panelderoite,new paneles.pnlSentiment());
        Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
    }//GEN-LAST:event_btn_SentimentMouseClicked

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
        // TODO add your handling code here:
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        panelhome.setVisible(false);
        new CambiaPanel(panelderoite,new paneles.pnlDashboard());
        Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
    }//GEN-LAST:event_btn_dashboardMouseClicked

    private void btn_ComponentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ComponentMouseClicked
        // TODO add your handling code here:
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        panelhome.setVisible(false);
        new CambiaPanel(panelderoite,new paneles.pnlCompanent());
        Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
    }//GEN-LAST:event_btn_ComponentMouseClicked

    private void btn_groupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_groupMouseClicked
        // TODO add your handling code here:
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        panelhome.setVisible(false);
        new CambiaPanel(panelderoite,new paneles.pnlGroup());
        Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
    }//GEN-LAST:event_btn_groupMouseClicked

    private void lmodelsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lmodelsMouseClicked
        // TODO add your handling code here:
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        int position = this.panelderoite.getX();
        if (position > 1199){
            Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
        }else{
            Animacion.Animacion.mover_derecha(60, 1200, 2, 2, panelderoite);
        }
        panelhome.setVisible(true); 
    }//GEN-LAST:event_lmodelsMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        panelhome.setVisible(false);
        new CambiaPanel(panelderoite,new paneles.pnlpreparation());
        Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        panelhome.setVisible(false);
        new CambiaPanel(panelderoite,new paneles.pnlAnalysis());
        Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        panelhome.setVisible(false);
        new CambiaPanel(panelderoite,new paneles.pnlSentiment());
        Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        panelhome.setVisible(false);
        new CambiaPanel(panelderoite,new paneles.pnlDashboard());
        Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        panelhome.setVisible(false);
        new CambiaPanel(panelderoite,new paneles.pnlCompanent());
        Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        panelhome.setVisible(false);
        new CambiaPanel(panelderoite,new paneles.pnlGroup());
        Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel16MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseMoved
        // TODO add your handling code here:
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jLabel16MouseMoved

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        // TODO add your handling code here:
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel21MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseMoved
        // TODO add your handling code here:
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jLabel21MouseMoved

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        panelhome.setVisible(false);
        new CambiaPanel(panelderoite,new paneles.pnlpreparation());
        Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
        // TODO add your handling code here:
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jLabel21MouseExited

    private void jLabel22MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseMoved
        // TODO add your handling code here:
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jLabel22MouseMoved

    private void jLabel22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseExited
        // TODO add your handling code here:
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jLabel22MouseExited

    private void jLabel20MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseMoved
        // TODO add your handling code here:
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jLabel20MouseMoved

    private void jLabel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseExited
        // TODO add your handling code here:
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jLabel20MouseExited

    private void jLabel24MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseMoved
        // TODO add your handling code here:
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jLabel24MouseMoved

    private void jLabel24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseExited
        // TODO add your handling code here:
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jLabel24MouseExited

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jLabel1MouseMoved

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel23MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseMoved
        // TODO add your handling code here:
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jLabel23MouseMoved

    private void jLabel23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseExited
        // TODO add your handling code here:
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jLabel23MouseExited

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        panelhome.setVisible(false);
        new CambiaPanel(panelderoite,new paneles.pnlAnalysis());
        Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        panelhome.setVisible(false);
        new CambiaPanel(panelderoite,new paneles.pnlSentiment());
        Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        panelhome.setVisible(false);
        new CambiaPanel(panelderoite,new paneles.pnlDashboard());
        Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        panelhome.setVisible(false);
        new CambiaPanel(panelderoite,new paneles.pnlCompanent());
        Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if(!panelderoite.isVisible()){panelderoite.setVisible(true);}
        panelhome.setVisible(false);
        new CambiaPanel(panelderoite,new paneles.pnlGroup());
        Animacion.Animacion.mover_izquierda(1200, 60, 2, 2, panelderoite);
    }//GEN-LAST:event_jLabel1MouseClicked

    
    void setColor(JPanel panel)
    {
        panel.setBackground(new Color(85,65,113));
    }
    
    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(64,43,100));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home_pgs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home_pgs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home_pgs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home_pgs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home_pgs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btn_Analysis;
    private javax.swing.JPanel btn_Component;
    private javax.swing.JPanel btn_Preparation;
    private javax.swing.JPanel btn_Sentiment;
    private javax.swing.JPanel btn_dashboard;
    private javax.swing.JPanel btn_group;
    private javax.swing.JPanel btn_home;
    private javax.swing.JLabel framedrag;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lmodels;
    private javax.swing.JPanel panelderoite;
    private javax.swing.JPanel panelhome;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
}
