/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package paneles;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Timer;
import java.util.TimerTask;
import static paneles.DemoReaderFile.readFile;


/**
 *
 * @author bouafia
 */
public class pnlSentiment extends javax.swing.JPanel {

    /**
     * Creates new form pnlhome
     */
    static int AL = 0;
    static String ML = "";
    static int d1 = 0, d2 = 0, d3 = 0, d4 = 0;
    static String save_es ="";
    static String start_pred ="";
    static String conn_tweet ="";
    static String load_model ="";
    static int counter1 = 0;
   
    public static void write(String s, File f) throws IOException{
        FileWriter fw = new FileWriter(f);
        fw.write(s);
        fw.close();
    }
    
    public pnlSentiment() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1140, 670));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(110, 89, 222));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 18)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/4230300-128.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, 110));

        jLabel19.setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 48)); // NOI18N
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setText("Sentiment analysis Tweet________");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 70));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 900, 130));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/211.png"))); // NOI18N
        jLabel23.setPreferredSize(new java.awt.Dimension(100, 100));
        jLabel23.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel23MouseMoved(evt);
            }
        });
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel23MouseExited(evt);
            }
        });
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 230, 220));

        jLabel25.setFont(new java.awt.Font("Nimbus Roman No9 L", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(54, 33, 89));
        jLabel25.setText("Sentiment analysis Tweet");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 10, 330));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 50, 255), 2));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tweet");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 430, 60, 25));

        jButton1.setText("<html><center>Start Sentiment <p>Analysis</center></htmp>");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 610, 130, 50));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 50, 255), 2));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Prediction");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 90, 25));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html><center>Logistic Regretion <p> Model</center></html>");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7)
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 241, 145, 37));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ML Model");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, 230, 20));

        jComboBox2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 290, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/output-onlinepngtools (11).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, 480));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 10, 170));

        jComboBox1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DecesionTree_En", "LogisticRegression_En", "SVM_En", "RandomForest_En", "NaiveBayes_En", "OneVsRest_En", "DecesionTree_Ar", "LogisticRegression_Ar", "SVM_Ar", "RandomForest_Ar", "NaiveBayes_Ar", "OneVsRest_Ar" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 230, 30));

        jTextField1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 230, 30));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Index In BDD Elasticsearch");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 230, 20));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hashtage");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 230, 20));

        jPanel2.setBackground(new java.awt.Color(110, 89, 222));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 18)); // NOI18N
        jLabel20.setForeground(java.awt.Color.white);
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sentiment_analysis/images/4230300-128.png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, 110));

        jLabel21.setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 48)); // NOI18N
        jLabel21.setForeground(java.awt.Color.white);
        jLabel21.setText("Sentiment analysis Tweet________");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 70));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 900, 130));

        jTextField2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 230, 30));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Machine Learning Algo");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, 230, 20));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Link Kibana");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 90, 20));

        jTextField7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 90, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 475, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel23MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseMoved
        // TODO add your handling code here:
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jLabel23MouseMoved

    private void jLabel23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseExited
        // TODO add your handling code here:
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jLabel23MouseExited

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            File f1 = new File("/home/bouafia/script_project/SA/send/linkkibana.txt");
            write(jTextField7.getText(),f1);
            File f2 = new File("/home/bouafia/script_project/SA/send/indexes.txt");
            write(jTextField1.getText(),f2);
            File f3 = new File("/home/bouafia/script_project/SA/send/hashtage.txt");
            write(jTextField2.getText(),f3);
            String NM = jComboBox2.getSelectedItem().toString();
            File f4 = new File("/home/bouafia/script_project/SA/send/mlmodel.txt");
            write("hdfs://master:9000/dz/cerist/pgs/bigdata/spark/"+NM.substring(0, NM.length()-5),f4);
        }catch (IOException e){
            
        }
        try {           
            Process proc1 = Runtime.getRuntime().exec("sh /home/bouafia/script_project/SA/RemoteText.sh");
            } catch (IOException e) {
            System.out.println(e.getMessage());
        }
        Timer timer = new Timer();
        counter1=0;
        TimerTask task = new TimerTask(){
            public void run(){
                counter1++;
                if(jComboBox1.getSelectedIndex()==0){
                    try {
                        Process proc1 = Runtime.getRuntime().exec("sh /home/bouafia/script_project/SA/DecesionTree.sh");                        
                    } catch (IOException e) {
                        System.out.println(e.getMessage());
                    }
                    jLabel7.setText("<html><center>DecesionTree<p>Model</center></html>");
                }
                if(jComboBox1.getSelectedIndex()==1){
                    try {
                        Process proc1 = Runtime.getRuntime().exec("sh /home/bouafia/script_project/SA/LogisticRegression.sh");    
                    } catch (IOException e) {
                        System.out.println(e.getMessage());
                    }
                    jLabel7.setText("<html><center>LogisticRegression<p>Model</center></html>");                    
                }
                if(jComboBox1.getSelectedIndex()==2){
                    try {
                        Process proc1 = Runtime.getRuntime().exec("sh /home/bouafia/script_project/SA/SVM.sh");            
                    } catch (IOException e) {
                        System.out.println(e.getMessage());
                    }
                    jLabel7.setText("<html><center>SVM<p>Model</center></html>");                    
                }
                if(jComboBox1.getSelectedIndex()==3){
                    try {
                        Process proc1 = Runtime.getRuntime().exec("sh /home/bouafia/script_project/SA/RandomForest.sh");            
                    } catch (IOException e) {
                        System.out.println(e.getMessage());
                    }
                    jLabel7.setText("<html><center>RandomForest<p>Model</center></html>");                    
                }
                if(jComboBox1.getSelectedIndex()==4){
                    try {
                        Process proc1 = Runtime.getRuntime().exec("sh /home/bouafia/script_project/SA/NaiveBayes.sh");            
                    } catch (IOException e) {
                        System.out.println(e.getMessage());
                    }
                    jLabel7.setText("<html><center>NaiveBayes<p>Model</center></html>");
                }
                if(jComboBox1.getSelectedIndex()==5){
                    try {
                        Process proc1 = Runtime.getRuntime().exec("sh /home/bouafia/script_project/SA/OneVsRest.sh");            
                    } catch (IOException e) {
                        System.out.println(e.getMessage());
                    }
                    jLabel7.setText("<html><center>OneVsRest<p>Model</center></html>");
                }
                if(jComboBox1.getSelectedIndex()==6){
                    try {
                        Process proc1 = Runtime.getRuntime().exec("sh /home/bouafia/script_project/SA/DecesionTreeAr.sh");            
                    } catch (IOException e) {
                        System.out.println(e.getMessage());
                    }
                    jLabel7.setText("<html><center>DecesionTree<p>Model</center></html>");
                }
                if(jComboBox1.getSelectedIndex()==7){
                    try {
                        Process proc1 = Runtime.getRuntime().exec("sh /home/bouafia/script_project/SA/LogisticRegressionAr.sh");            
                    } catch (IOException e) {
                        System.out.println(e.getMessage());
                    }
                    jLabel7.setText("<html><center>LogisticRegression<p>Model</center></html>");
                }        
                if(jComboBox1.getSelectedIndex()==8){
                    try {
                        Process proc1 = Runtime.getRuntime().exec("sh /home/bouafia/script_project/SA/SVMAr.sh");            
                    } catch (IOException e) {
                        System.out.println(e.getMessage());
                    }
                    jLabel7.setText("<html><center>SVM<p>Model</center></html>");
                }
                if(jComboBox1.getSelectedIndex()==9){
                    try {
                        Process proc1 = Runtime.getRuntime().exec("sh /home/bouafia/script_project/SA/RandomForestAr.sh");            
                    } catch (IOException e) {
                        System.out.println(e.getMessage());
                    }
                    jLabel7.setText("<html><center>RandomFores<p>Model</center></html>");
                }
                if(jComboBox1.getSelectedIndex()==10){
                    try {
                        Process proc1 = Runtime.getRuntime().exec("sh /home/bouafia/script_project/SA/NaiveBayesAr.sh");            
                    } catch (IOException e) {
                        System.out.println(e.getMessage());
                    }
                    jLabel7.setText("<html><center>NaiveBayes<p>Model</center></html>");
                }
                if(jComboBox1.getSelectedIndex()==11){
                    try {
                        Process proc1 = Runtime.getRuntime().exec("sh /home/bouafia/script_project/SA/OneVsRestAr.sh");            
                    } catch (IOException e) {
                        System.out.println(e.getMessage());
                    }
                    jLabel7.setText("<html><center>OneVsRest<p>Model</center></html>");
                }
                if(counter1==1){
                    timer.cancel();
                }
            }
        };
        timer.scheduleAtFixedRate(task, 30000, 2000);
        Timer timer1 = new Timer(); 
        TimerTask task1 = new TimerTask(){
            public void run(){
                try{
                    Runtime.getRuntime().exec("sh /home/bouafia/script_project/SA/load_result.sh"); 
                    } catch (IOException e) {
                    System.out.println(e.getMessage());
                }
            }
        };
        timer1.scheduleAtFixedRate(task1, 50000, 20000);
        Timer timer2 = new Timer();
 
        TimerTask task2 = new TimerTask(){
            public void run(){
                load_model = readFile("/home/bouafia/script_project/SA/receive/load_model.txt");
                if(load_model.equalsIgnoreCase("true") && d1==0){
                    jPanel5.setBackground(new Color(51,196,37));
                    d1=1;
                }
                conn_tweet = readFile("/home/bouafia/script_project/SA/receive/conn_tweet.txt");
                if(conn_tweet.equalsIgnoreCase("true") && d2==0){
                    jPanel4.setBackground(new Color(51,196,37));
                    d2=1;
                }
                start_pred = readFile("/home/bouafia/script_project/SA/receive/start_pred.txt");
                if(start_pred.equalsIgnoreCase("true") && d3==0){
                    jPanel6.setBackground(new Color(51,196,37));
                    d3=1;
                }
                save_es = readFile("/home/bouafia/script_project/SA/receive/save_es.txt");                
                if(save_es.equalsIgnoreCase("true") && d4==0){
                    jPanel3.setBackground(new Color(160,246,162));
                    d4=1;
                    timer1.cancel();
                    timer2.cancel();
                }                
            }
        };
        timer2.scheduleAtFixedRate(task2, 70000, 20000); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        try{
            BufferedReader in = new BufferedReader(new FileReader("/home/bouafia/script_project/ML/send/listmodel.txt"));
            String line = null;
            jComboBox2.removeAllItems();
            AL = jComboBox1.getSelectedIndex();
            if(AL == 0){ML ="DT";}else if(AL == 1){ML ="LR";}else  if(AL == 2){ML ="SVM";}else if(AL == 3){ML ="RF";}else if(AL == 4){ML ="NB";}else if(AL == 5){ML ="OVR";}
            if(AL == 6){ML ="ADT";}else if(AL == 7){ML ="ALR";}else  if(AL == 8){ML ="ASVM";}else if(AL == 9){ML ="ARF";}else if(AL == 10){ML ="ANB";}else if(AL == 11){ML ="AOVR";}
            while((line = in.readLine()) != null){
                if(line.startsWith(ML)){
                    jComboBox2.addItem(line.substring(ML.length()+1));
                }
            }
         }catch(IOException e){
             e.printStackTrace();
         }
    }//GEN-LAST:event_jComboBox1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
